name: Actualizar Agenda PirloTV
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar Scraper Bot
        env:
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
        run: python scraper_bot.py
